### ISSUE TITLE
Ion mobility data supported

### ISSUE THREAD

**Issue by hsiaoyi0504** [lgatto/synapter#105]
I have a question about this library, is it suitable for Ion mobility data?
I use Synapt G2 mass spectrometer also.

**Comment by lgatto** [comment]
Yes, you can use `synapter` with ion mobility. We did all the development using data acquired on a Synapt G2 instrument. See the [package vignette](http://bioconductor.org/packages/release/bioc/vignettes/synapter/inst/doc/synapter.pdf) and [this reference](http://www.ncbi.nlm.nih.gov/pubmed/23510225) ([pdf](http://cpu.sysbiol.cam.ac.uk/papers/Bond2013.pdf)) for details. Let us know if you have more questions.

**Comment by hsiaoyi0504** [comment]
Do you know how to convert the raw data to any kinds of format?

**Comment by pavel-shliaha** [comment]
Does your data have mobility dimension?

**Comment by hsiaoyi0504** [comment]
Yes

**Comment by pavel-shliaha** [comment]
I am not sure there is an open data format for mobility data. Formats like mzXML/mzML contain individual spectra that correpsond to a certain retention time. An "open data format" for mobility data means that every scan is assigned a retention time and drift time. I am not sure that mass spectrometry community has worked out such a format. If you question is how to extract such data from raw files using any software then I have heard that "protein wizard" authors have been working on it. Otherwise you can ask Waters for a C++ script like I did to extract data, like I did for my paper: "Additional precursor purification in isobaric mass tagging experiments by traveling wave ion mobility separation (TWIMS)." Please note that you are not the first person who asks: before you I got the same question from Adam Cryar and Daniel Nightingale. I suggest you email Hans Vissers and ask him to finally implement ion mobility data conversion into a readable format in PLGS. The more people email him and ask the faster you'll get the software.

**Comment by pavel-shliaha** [comment]
Forgot to mention: new synapter version has mobility matching of fragments to precursors, but:
1) it works with XML files, in which fragment EMRTs have been matched to precursors
2) it only works for HDMSE, not IMS-DDA like in the aforementioned paper

**Comment by hsiaoyi0504** [comment]
OK, thank you for your reply.
But I still have one question, what do you mean a retention time and drift time? I think it's the same thing, or maybe I am wrong....

**Comment by pavel-shliaha** [comment]
No they are not the same. If you look at "normal" LC-MS/MS data at every point of retention time you have a spectrum (MS1 or MS2). In LC-IMS-MS data at every point of retention time you have a "block", which is composed of 200 spectra. The number of spectrum in the "block" represents the drift time. 
![capture](https://cloud.githubusercontent.com/assets/1895805/13240218/1e4c3cc0-d9e1-11e5-97c3-22d7a881c30e.JPG)

So as a result you can find precursor in three dimensions in 
1) MS (position in the spectrum)
2) in IMS (number of spectrum in which your precursor is in the block)
3) in retention time (the time in the run in which your spectrum has been acquired)

Hence the problem of extracting data in open format.

**Comment by hsiaoyi0504** [comment]
But in the LC-IMS case, they are the same or maybe we should say there are only retention time?

**Comment by pavel-shliaha** [comment]
LC-IMS? I dont understand. What instrument are you running? Dont you have MS?

**Comment by hsiaoyi0504** [comment]
Oops, maybe I misunderstand that your LC-IMS-MS as a kind of tandem mass
And I think what I want to ask is that for the case of IMS-MS.

**Comment by pavel-shliaha** [comment]
I think I might have an answer for you after all. As far as I remember you can go to driftscope and remove 1 dimension of data preserving either retention time (in your case time of acquisition) or drift time in a fileof LC-MS format. So ask your collaborators to do that and then you will have a file which looks like LC-MS, but LC will represent IMS. You can then export this file using MSConvert in mzML from Proteowizard. That of course means they will have to click through all the files though.
