### ISSUE TITLE
bug of modelling function. Let user set max RT difference.

### ISSUE THREAD

**Issue by pavel-shliaha** [lgatto/synapter#107]
there is currently a bug in synapter behaviour, which I think can be attributed to modelling by LOWESS. During master construction from 

"S130423_05_IA_final_peptide.csv" 
"S130423_07_IA_final_peptide.csv"
"S130423_14_IA_final_peptide.csv"

files all the acqusitions show reasonable RT drift from each other. 

05 against 07
![image](https://cloud.githubusercontent.com/assets/1895805/12178976/a8647dd2-b574-11e5-86be-1ebaf10d7cba.png)

05 against 14

![image](https://cloud.githubusercontent.com/assets/1895805/12178997/c41dd00a-b574-11e5-8b65-6e7f523ae873.png)

All peptides also elute between 0 and 200 min. However after master construction master contains peptides that elute at up to 1200 min. Clearly this is a failure of rt modelling during master construction, when model has predicted a rt for a peptide at 1200 minutes. I think this happens due to peptide outliers (even though LOWESS is supposed to deal with outliers). I would like to suggest to put an option to set a reasonable max deviation for a peptide from one run to another (say 10 min), i.e. if a peptide differs more than 10 min from one run to another, then it is not considered during rt modelling. 

Note the same is done by Waters in expression (where we took the lowess idea from)

http://www.ncbi.nlm.nih.gov/pubmed/15801753

**Comment by sgibb** [comment]
While looking at this issue I found something strange. 
Is there any reason why we use two different kind of `loess` estimators?

- 1. Ident vs Quant (default `synergize` workflow; via `modelRetTime`):
```
lo <- loess(deltaRt ~ precursor.retT.ident, data = xx, span = span,
            degree = 1, family = "symmetric", iterations = 4, surface = "direct")
 ```


- 2. master creation (`makeMaster`)
```
RtModel <- loess(precursor.retT.master ~ precursor.retT.slave,
                 data = mergedPeptideData, span = span)
```

There are at least two important differences:
1. We model `diff(rt) ~ rt.ident` and `rt.master ~ rt.slave`.
2. We use `symmetric` (means a M-estimator based on Tukey's biweight function) and `least-squares`.

I think we should use the same for both. I would prefer the first approach (but this would be much slower).
@lgatto any comments?

**Comment by pavel-shliaha** [comment]
There should be no difference. The LOESS modelling should be the same between synergise and master construction. Perhaps this difference is the reason for the artifact described above?

**Comment by lgatto** [comment]
Good point... I don't know. I looked back and it seems this has always been like that. Feel free to go ahead and amend. Could you run a few loess models using the 2 approaches to assess how much of a difference that makes?

**Comment by sgibb** [comment]
Finally I found some time to test the different models.
1. There is no difference between `diff(rt) ~ rt.ident` and `rt.master ~ rt.slave` (obviously it is just a constant shift).
2. There is an impact of the chosen `family` argument `"symmetric"` (m estimator) or `"gaussian"` (least squares). As we assumed the m estimator approach seems to be more stable:

*05 vs 07*:

![1-0 05](https://cloud.githubusercontent.com/assets/1828443/12261594/5661d35c-b922-11e5-8b0d-661188b2d1ce.png)

timings:
```r
# least sq
   user  system elapsed 
  4.668   0.000   4.670 
# least sq diff
   user  system elapsed 
  4.684   0.000   4.685 
# m interpolate
   user  system elapsed 
  9.832   0.000   9.832 
# m direct 
   user  system elapsed 
272.596   0.000 272.561 
```

Summary of original and predicted values.

```r
                Min. 1st Qu. Median  Mean 3rd Qu.  Max.  NA's
master         23.39   49.54  76.42 82.94   112.1 194.1     0
slave          23.39   49.54  76.42 82.94   112.1 194.1     0
least sq      -28.34   51.77  81.87 85.79   115.2 194.8 43809
least sq diff -28.34   51.77  81.86 85.78   115.2 194.8 43809
m interpolate  22.20   50.34  78.14 83.84   113.1 194.1     0
m direct       22.20   50.32  78.11 83.81   113.0 194.1     0
```
The m estimator could be calculated `direct` or by `interpolation`. `direct` yields slightly better results but takes much more time. Master creation takes already much time and is done only once so IMHO it doesn't matter whether the `loess` model takes 10 seconds or 4 minutes. That's why I would keep `direct` as we did all the time in `synergise`.

Next steps:
- I am going to rewrite `makeMaster` using the `"symmetric"` loess approach that we used in `synergise` for synapter 2.0. Should we backport this to synapter 1?
- Also I think it would be improve the estimator if we exclude large outliers before (as @pavel-shliaha asked for in this issue and as it is done by Waters, too).

**Comment by lgatto** [comment]
> I am going to rewrite makeMaster using the "symmetric" loess approach that we used in synergise for synapter 2.0. Should we backport this to synapter 1?

I am not convinced it is a good idea to backport if the goal is the get`synapter` 2.0 ready for next release. We would have `synapter` v1.x, `synapter` v1.x' with `symmetric` loess for a couple of month and then `synapter` v2. 

> Also I think it would be improve the estimator if we exclude large outliers before (as @pavel-shliaha asked for in this issue and as it is done by Waters, too).

Ok, sounds reasonable.

**Comment by sgibb** [comment]
I changed the `loess` modeling to `symmetric` as discussed above. Additionally I add @pavel-shliaha 's wish to set a max rt difference but I am not sure that this works good (e.g. we get negative rt predictions, I am not sure why this happen): 

Creating a master of the following three files:
 - "S130423_05_IA_final_peptide.csv"
 - "S130423_07_IA_final_peptide.csv"
 - "S130423_14_IA_final_peptide.csv"

```r
                Min. 1st Qu. Median   Mean 3rd Qu.   Max.
2.0.1          19.68   50.25  72.94  81.45   110.3  194.1 # old loess ("gaussian")
2.0.2          16.88   51.65  79.00 109.90   117.3 1152.0 # old loess ("gaussian"); rt > 120
issue107.1     15.27   49.97  72.87  81.40   109.9  194.1 # new loess ("symmetric")
issue107.2     15.65   50.37  78.22  82.37   110.2  194.1 # new loess ("symmetric")
issue107-10.1 -47.83   49.69  72.93  81.31   109.9  194.1 # new loess + max rt == 10 min
issue107-10.2 -47.83   50.41  73.32  81.23   109.6  193.0 # new loess + max rt == 10 min
```

Unfortunately the time to create a master file increased dramatically (without fragment library): 320 sec vs 7200 sec

**Comment by lgatto** [comment]
Could you elaborate on these negative values? I don't understand why this leads to negative values. Does the RT filtering not mean remove peptides that have a delta RT > 10 minutes prior to modelling?

**Comment by pavel-shliaha** [comment]
Agree with Laurent, filtering should not be an issue. Could you please also make the max rt difference a parameter a user can choose (default = 10 min)?

**Comment by pavel-shliaha** [comment]
1) A stupid question: are you sure there hasn't been a mix up of seconds and minutes?
2) is it only 1 peptide (i.e. does this peptide perhaps have the lowest  rt?) that becomes -47 min or is it a trend among many peptides being added to the master? Could you perhaps plot it for us, as you did above?

**Comment by sgibb** [comment]
I will investigate this (maybe it is something stupid like mixing up seconds and minutes).

Beside this I have another question. Currently we don't run the model on unique peptide sequences. This results in an overweighting of some retention times. When creating a master from 05 and 14 we have a data.frame of ~17000 and ~22000 rows. After merging (because of duplicated peptide sequences and multiple combinations of these rows) we get a data.frame with ~90000 rows for the model. The duplicated peptide sequences have the same rt, e.g.:

master (05):

"protein.Accession"|"protein.Description"|"protein.dataBaseType"|"protein.falsePositiveRate"|"peptide.matchType"|"peptide.mhp"|"peptide.seq"|"peptide.score"|"precursor.leID"|"precursor.mhp"|"precursor.retT"|"precursor.inten"|"precursor.z"|"precursor.mz"|"precursor.Mobility"|"errorppm"|"pval"|"qval"|"BH"|"Bonferroni"
-------------------|---------------------|----------------------|---------------------------|-------------------|-------------|-------------|---------------|----------------|---------------|----------------|-----------------|-------------|--------------|--------------------|----------|------|------|----|------------
"P06733"|"Alpha-enolase OS=Homo sapiens GN=ENO1 PE=1 SV=2"|"Regular"|0|"PepFrag1"|800.3825|"YDLDFK"|8.1393|78610|800.3849|72.882|64983|2|400.6961|27.482|2.9985663104403|0|0|0|0
"P00925"|"Enolase 2 OS=Saccharomyces cerevisiae GN=ENO2 PE=1 SV=2"|"Regular"|0|"PepFrag1"|800.3825|"YDLDFK"|8.1393|78610|800.3849|72.882|64983|2|400.6961|27.482|2.9985663104403|0|0|0|0
"P00924"|"Enolase 1 OS=Saccharomyces cerevisiae GN=ENO1 PE=1 SV=2"|"Regular"|0|"PepFrag1"|800.3825|"YDLDFK"|8.1393|78610|800.3849|72.882|64983|2|400.6961|27.482|2.9985663104403|0|0|0|0
"C8Z9E6"|"Eno1p OS=Saccharomyces cerevisiae (strain Lalvin EC1118 / Prise de mousse) GN=EC1118_1G1_5908g PE=3 SV=1"|"Regular"|0|"PepFrag1"|800.3825|"YDLDFK"|8.1393|78610|800.3849|72.882|64983|2|400.6961|27.482|2.9985663104403|0|0|0|0
"P13929"|"Beta-enolase OS=Homo sapiens GN=ENO3 PE=1 SV=5"|"Regular"|0|"PepFrag1"|800.3825|"YDLDFK"|8.1393|78610|800.3849|72.882|64983|2|400.6961|27.482|2.9985663104403|0|0|0|0
"P09104"|"Gamma-enolase OS=Homo sapiens GN=ENO2 PE=1 SV=3"|"Regular"|0|"PepFrag1"|800.3825|"YDLDFK"|8.1393|78610|800.3849|72.882|64983|2|400.6961|27.482|2.9985663104403|0|0|0|0

slave (14):

"protein.Accession"|"protein.Description"|"protein.dataBaseType"|"protein.falsePositiveRate"|"peptide.matchType"|"peptide.mhp"|"peptide.seq"|"peptide.score"|"precursor.leID"|"precursor.mhp"|"precursor.retT"|"precursor.inten"|"precursor.z"|"precursor.mz"|"precursor.Mobility"|"errorppm"|"pval"|"qval"|"BH"|"Bonferroni"
-------------------|---------------------|----------------------|---------------------------|-------------------|-------------|-------------|---------------|----------------|---------------|----------------|-----------------|-------------|--------------|--------------------|----------|------|------|----|------------
"P00925"|"Enolase 2 OS=Saccharomyces cerevisiae GN=ENO2 PE=1 SV=2"|"Regular"|0|"PepFrag1"|800.3825|"YDLDFK"|8.4848|81822|800.3831|73.4953|72278|2|400.6952|27.549|0.749641577574565|0|0|0|0
"P06733"|"Alpha-enolase OS=Homo sapiens GN=ENO1 PE=1 SV=2"|"Regular"|0|"PepFrag1"|800.3825|"YDLDFK"|8.4848|81822|800.3831|73.4953|72278|2|400.6952|27.549|0.749641577574565|0|0|0|0
"P00924"|"Enolase 1 OS=Saccharomyces cerevisiae GN=ENO1 PE=1 SV=2"|"Regular"|0|"PepFrag1"|800.3825|"YDLDFK"|8.4848|81822|800.3831|73.4953|72278|2|400.6952|27.549|0.749641577574565|0|0|0|0
"C8Z9E6"|"Eno1p OS=Saccharomyces cerevisiae (strain Lalvin EC1118 / Prise de mousse) GN=EC1118_1G1_5908g PE=3 SV=1"|"Regular"|0|"PepFrag1"|800.3825|"YDLDFK"|8.4848|81822|800.3831|73.4953|72278|2|400.6952|27.549|0.749641577574565|0|0|0|0
"P13929"|"Beta-enolase OS=Homo sapiens GN=ENO3 PE=1 SV=5"|"Regular"|0|"PepFrag1"|800.3825|"YDLDFK"|8.4848|81822|800.3831|73.4953|72278|2|400.6952|27.549|0.749641577574565|0|0|0|0
"P09104"|"Gamma-enolase OS=Homo sapiens GN=ENO2 PE=1 SV=3"|"Regular"|0|"PepFrag1"|800.3825|"YDLDFK"|8.4848|81822|800.3831|73.4953|72278|2|400.6952|27.549|0.749641577574565|0|0|0|0

I would suggest to keep only unique peptide sequences for master creation. Or is this incorrect?

**Comment by pavel-shliaha** [comment]
Of course! I am very surprised by this. What about FDR estimation, does it run on unique peptides at least?

**Comment by sgibb** [comment]
1. Regarding the problem with negative rt's. I indeed mixed up a `-` and a `+` in the prediction. Sorry for that. (I shouldn't code late at night.)
2. FDR estimation: I never investigated the FDR estimation code. A quick look shows some `unique(peptide.seq)` calls. So I think it should work as expected. I will investigate this later.
3. After using `unique(peptide.seq)` the new loess model (using the m estimator) is very fast (around 200 sec on the above test set and ~10000 common peptides (in contrast to 7200 sec and ~90000 combinations of "common" peptides).
4. The `maxRtDiff` argument doesn't have a large impact on the new model but on the old one (new: m estimator; old: least squares). That's why I would suggest to set the default `maxRtDiff` value to `Inf` (means no filtering) instead of 10 min. See the following images for illustration (span = 0.05 [default], maxRtDiff = Inf, 10 min, 5 min; black dots = original diff rt, red dots = least square loess model, blue dots = m estimator loess model):

![model_span0 05_maxrtinf](https://cloud.githubusercontent.com/assets/1828443/12529933/7bc1505c-c1cc-11e5-94b6-ffde3472a8d9.png)
![model_span0 05_maxrt10](https://cloud.githubusercontent.com/assets/1828443/12529934/7dce0142-c1cc-11e5-9b36-0799683dfc35.png)
![model_span0 05_maxrt05](https://cloud.githubusercontent.com/assets/1828443/12529936/800e7ee6-c1cc-11e5-8eef-fc89d192c620.png)

I am going to merge the new model into the `2.0` branch and recreate all master files for the Kuharev data sets.
