### ISSUE TITLE
bug in filterNonUniqueMatches

### ISSUE THREAD

**Issue by pavel-shliaha** [lgatto/synapter#114]
the files and code are in: synapter2paper\\bugs

> filterNonUniqueMatches(synapterAnalysis, minDelta = nonUniqueThreshold)
Error in `[<-.data.frame`(`*tmp*`, rows[keep], cols, value = list(precursor.leID.quant = c(7620,  : 
  missing values are not allowed in subscripted assignments of data frames

**Comment by sgibb** [comment]
JFTR: the reason for the bug was in the `.fragmentMatchingDifferences` function (but hits the `filterNonUniqueMatches` function) that looks for `non-unique-true` and `non-unique-false` matches but ignores the newly introduces `no-quant-id` result (which could contain multiple matches, too). Now we treat all matches with more than 1 match as non-unique onces.
