### ISSUE TITLE
add distribution of common fragments between master and all quant dataset

### ISSUE THREAD

**Issue by pavel-shliaha** [lgatto/synapter#115]
Synapter 2.0 performs less effectively on G2 data as we saw from organelle proteomics dataset. This happens because the merged peptides in quant run have more common peptides than the general population. This is expected since the merged peptides are the ones that got identified at low FDR hence their spectra is of higher quality. TO solve this problem I suggest to add a third plot to plotFragmentMatchingPerformance(). Note this plot will only contain one line since there are no more TRUE and FALSE positive matches

**Comment by sgibb** [comment]
Instead of adding a new plot we could simply add a new line:
![fmperf](https://cloud.githubusercontent.com/assets/1828443/16465211/de9df110-3e3d-11e6-9928-d2d50874c177.png)

Now the differences between true and false matches are not really visible anymore. What about log the y-axis?
![fmperflog](https://cloud.githubusercontent.com/assets/1828443/16465237/fafbbefa-3e3d-11e6-9d0d-06e7dc88cf26.png)
(BTW: nice linear slope for "all peptides" and "true matches" in log space)

Or should we use a barchart (which could be right but looks even worse)?
![fmperf2](https://cloud.githubusercontent.com/assets/1828443/16465276/31b58098-3e3e-11e6-913d-6eeb403f5e6d.png)

What do you think? Do you have a better idea for a plot?

**Comment by pavel-shliaha** [comment]
I would still prefer a new plot ))). The reason is that there is much more peptides in full dataset than there are in the merged dataset and so the merged dataset gets compressed

**Comment by sgibb** [comment]
Ok I added an argument `showAllPeptides` (default `FALSE`) to the `plotFragmentMatchingPerformance` function. `TRUE` would create the first of the three plots above and `FALSE` the original one.
