### ISSUE TITLE
NEWS is old on bioc devel

### ISSUE THREAD

**Issue by sgibb** [lgatto/synapter#137]
The NEWS file presented on https://bioconductor.org/packages/devel/bioc/html/synapter.html is the old one (`1.13.1`). Similar to `MSnbase` we replaced the NEWS file by a NEWS.md. Could you please run `make PKG=synapter NEWS`, set the header from "Changes in 1.99.0" to "Changes in 2.0" and upload to bioc?
(maybe the same needs to be done for `MSnbase` as well)

**Comment by lgatto** [comment]
Thanks @sgibb. I will need to set up a hook to make sure that this doesn't happen anymore. Fro now, I have only kept `NEWS.md` in `synapter`, because the `NEWS` that was automatically generated still had the markdown markup for sections of level > 2. I guess that's an easy fix in `maker`, but I don't have time to check that now.
