### ISSUE TITLE
synapter bug

### ISSUE THREAD

**Issue by pavel-shliaha** [lgatto/synapter#90]
I am having trouble with analysing one particular acquisition and it produces the following error (R version 3.2.1)

I have put all the necessary files (master, fast, pep3d, spectrum.xml, final_fragment.csv and final_peptide.csv) into

    Z:\RAW\pvs22\_QTOF_DATA_data3\data_for_synapter_2.0\bug\2015_07_19_problems_with_loading_spectrum\for_synapter

```r
Convert spectra data.frames to MSnbase::Spectrum2 objects
  |===============================================================================================================================     |  96%
Error in ms2[i, "Mass"] : subscript out of bounds
```

**Comment by sgibb** [comment]
When I wrote this function the `LE_ID` and `HE_ID` (ids of the Low/High Energy Scans) were identically to the row number of the awkward table in the Spectrum.xml file. This is not true for this example file anymore. That's why we have to look up the row indices manually. Thanks to `findInterval` it is just a few milliseconds slower than the previous (wrong) solution (the spectrum import takes minutes ...).
